### ISSUE TITLE
redis以及redis分布式锁商用没啥问题吧？

### ISSUE THREAD

**Issue by walt-liuzw** [XiLife-OSPC/Masuit.Tools#2]
打算商用redishelper以及redis的分布式锁这两块，还没采坑
刚从csrediscore那边过来，那个框架超时很严重，经常连接不上...

**Comment by ldqk** [comment]
该项目中的redishelper是基于StackExchange的，可能效果不及csrediscore，如果csrediscore都不能满足你的需求的话，那可能只有考虑ServiceStack或者NewLife.Redis的了

**Comment by walt-liuzw** [comment]
> 该项目中的redishelper是基于StackExchange的，可能效果不及csrediscore，如果csrediscore都不能满足你的需求的话，那可能只有考虑ServiceStack或者NewLife.Redis的了

我看到现在netcore使用redis客户端  StackExchange大于csrediscore，而且ServiceStack是收费的吧
现在也是纠结选用哪个，因为做业务没有深入研究这些组件，作为商用，我们希望高可用稳定，这样的话 选择哪种最合适？

**Comment by ldqk** [comment]
以我的经验来看，csrediscore比StackExchange要稳定得多，我们目前也是主要使用csrediscore，根据服务器日志来看，csrediscore也只是极少情况下会断流；或许最新版的StackExchange 2.x有所改进，你可以试试看，但该项目中的redishelper是基于StackExchange 1.2.6的。

**Comment by walt-liuzw** [comment]
> 以我的经验来看，csrediscore比StackExchange要稳定得多，我们目前也是主要使用csrediscore，根据服务器日志来看，csrediscore也只是极少情况下会断流；或许最新版的StackExchange 2.x有所改进，你可以试试看，但该项目中的redishelper是基于StackExchange 1.2.6的。

我是使用该项目中的redishelper，但是底层换成了StackExchange 2.0

**Comment by ldqk** [comment]
嗯，可以对比看看吧

**Comment by nodyang** [comment]
BeetleX.Redis 你可以试试这个
