### ISSUE TITLE
关于日志功能的疑问

### ISSUE THREAD

**Issue by PyForMcj** [XiLife-OSPC/Masuit.Tools#3]
日志都只能写在一个日志文件下么，没找到自定义日志文件名字的地方？
比如说我有两个任务，我想分成两个文件写？

**Comment by ldqk** [comment]
没有这么高级的功能，还是建议考虑用标准化的日志库吧，比如log4net、NLog、Exceptionless之类的

**Comment by PyForMcj** [comment]
> 没有这么高级的功能，还是建议考虑用标准化的日志库吧，比如log4net、NLog、Exceptionless之类的

好吧。我就是一个Quartz调度，一开始想用NLog，嫌太重，发现博主这个插件，然后试了下。。。我晓得了~~
